# Generated by Django 3.0.1 on 2019-12-25 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.CharField(max_length=500)),
                ('price_quotation', models.IntegerField()),
                ('deadline', models.DateField()),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=700)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FreeLancer', to='user.Profile')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Employeer', to='user.Profile')),
                ('skills_required', models.ManyToManyField(to='user.Skill')),
            ],
        ),
    ]
